#Executive Summary


Insurance claims fraud detection using Decision tress and random forest along with with hyperparameter tuning

Abstract: A large number of problems in data mining are related to fraud detection. Fraud is a common problem in auto insurance claims, health insurance claims, credit card transactions, financial transaction and so on. The data in this particular case comes from an actual auto insurance company. Each record represents an insurance claim. The last column in the table tells you whether the claim was fraudulent or not.

A number of people have used this dataset and here are some observations from them:

• “This is interesting data because the rules that most tools are coming up with do not make any intuitive sense. I think a lot of the tools are overfitting the data set.”

• “The other systems are producing low error rates but the rules generated make no sense.”

• “It is OK to have a higher overall error rate with simple human-understandable rules for a business use case like this.”

Attribute Information: Input variables:

MONTH: Jan through Dec.

WEEKOFMONTH: Continuous – 1 through 5.

DAYOFWEEK: Monday through Sunday.

MAKE: Acura, BMW, Chevrolet, Dodge, Ford, Toyota, VW, Nissan, etc.

ACCIDENTAREA: Urban, Rural.

DAYOFWEEKCLAIMED: Monday through Friday.

MONTHCLAIMED: Jan through Dec.

WEEKOFMONTHCLAIMED: Continuous – 1 through 5.

SEX: Male/Female.

MARITALSTATUS: Married, Single, Divorced, Widow.

AGE: continuous – 0 through 80.

FAULT: Policy_Holder, Third_Party.

POLICYTYPE: Sport-Collision, Sedan-All_Perils, Sedan-Collision, Sedan-Liability etc.

VEHICLECATEGORY: Sport, Sedan, Utility, etc.

VEHICLEPRICE: 20000_to_29000,30000_to_39000, 40000_to_59000 etc.

REPNUMBER: Continuous – 1 through 16

DEDUCTIBLE: Continuous – 300 through 700.

DRIVERRATING: Continuous – 1 through 4.

#Libraries

In [1]:
import pandas as pd
from sklearn.preprocessing import label_binarize
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

In [35]:
trainData = pd.read_csv('Train (1).csv')
testData = pd.read_csv('Test (1).csv')

In [36]:
print(trainData.shape)
print(testData.shape)

(2999, 32)
(12918, 32)


In [37]:
#Understanding the Columns

trainData.info()
print()
testData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   MONTH                 2999 non-null   object
 1   WEEKOFMONTH           2999 non-null   int64 
 2   DAYOFWEEK             2999 non-null   object
 3   MAKE                  2999 non-null   object
 4   ACCIDENTAREA          2999 non-null   object
 5   DAYOFWEEKCLAIMED      2999 non-null   object
 6   MONTHCLAIMED          2999 non-null   object
 7   WEEKOFMONTHCLAIMED    2999 non-null   int64 
 8   SEX                   2999 non-null   object
 9   MARITALSTATUS         2999 non-null   object
 10  AGE                   2999 non-null   int64 
 11  FAULT                 2999 non-null   object
 12  POLICYTYPE            2999 non-null   object
 13  VEHICLECATEGORY       2999 non-null   object
 14  VEHICLEPRICE          2999 non-null   object
 15  REPNUMBER             2999 non-null   

In [38]:
# To check number of null values
trainData.isna().sum()

MONTH                   0
WEEKOFMONTH             0
DAYOFWEEK               0
MAKE                    0
ACCIDENTAREA            0
DAYOFWEEKCLAIMED        0
MONTHCLAIMED            0
WEEKOFMONTHCLAIMED      0
SEX                     0
MARITALSTATUS           0
AGE                     0
FAULT                   0
POLICYTYPE              0
VEHICLECATEGORY         0
VEHICLEPRICE            0
REPNUMBER               0
DEDUCTIBLE              0
DRIVERRATING            0
DAYS_POLICY_ACCIDENT    0
DAYS_POLICY_CLAIM       0
PASTNUMBEROFCLAIMS      0
AGEOFVEHICLE            0
AGEOFPOLICYHOLDER       0
POLICEREPORTFILED       0
WITNESSPRESENT          0
AGENTTYPE               0
NUMBEROFSUPPLIMENTS     0
ADDRESSCHANGE_CLAIM     0
NUMBEROFCARS            0
YEAR                    0
BASEPOLICY              0
FRAUDFOUND              0
dtype: int64

In [39]:
#To get list of names of all Columns from a dataframe

TrainCols = list(trainData.columns.values)
TestCols = list(testData.columns.values)
print(TrainCols)
print(TestCols)

['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'FRAUDFOUND']
['MONTH', 'WEEKOFMONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED', 'MONTHCLAIMED', 'WEEKOFMONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'AGE', 'FAULT', 'POLICYTYPE', 'VEHICLECATEGORY', 'VEHICLEPRICE', 'REPNUMBER', 'DEDUCTIBLE', 'DRIVERRATING', 'DAYS_POLICY_ACCIDENT', 'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE', 'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE', 'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS', 'YEAR', 'BASEPOLICY', 'F

In [40]:
#The below function returns a list of categorical features which are not numeric.
train_cat_cols = trainData.select_dtypes(exclude=['float','int']).columns #selecting the categorical columns
print(train_cat_cols.shape)
print(train_cat_cols)

(25,)
Index(['MONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED',
       'MONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'FAULT', 'POLICYTYPE',
       'VEHICLECATEGORY', 'VEHICLEPRICE', 'DAYS_POLICY_ACCIDENT',
       'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE',
       'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE',
       'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS',
       'BASEPOLICY', 'FRAUDFOUND'],
      dtype='object')


In [41]:
categoricalFeatures = ['MONTH', 'DAYOFWEEK', 'MAKE', 'ACCIDENTAREA', 'DAYOFWEEKCLAIMED',
       'MONTHCLAIMED', 'SEX', 'MARITALSTATUS', 'FAULT', 'POLICYTYPE',
       'VEHICLECATEGORY', 'VEHICLEPRICE', 'DAYS_POLICY_ACCIDENT',
       'DAYS_POLICY_CLAIM', 'PASTNUMBEROFCLAIMS', 'AGEOFVEHICLE',
       'AGEOFPOLICYHOLDER', 'POLICEREPORTFILED', 'WITNESSPRESENT', 'AGENTTYPE',
       'NUMBEROFSUPPLIMENTS', 'ADDRESSCHANGE_CLAIM', 'NUMBEROFCARS',
       'BASEPOLICY']


In [42]:
# Seperate Target column from Train Data
Xtrain = trainData[TrainCols[0:len(TrainCols)-1]].copy()
Ytrain = trainData[['FRAUDFOUND']].copy()
print("Train Set shape:")
print(Xtrain.shape)
print(Ytrain.shape)
Xtest = testData[TestCols[0:len(TestCols)-1]].copy()
Ytest = testData[['FRAUDFOUND']].copy()
print("Test Set shape:")
print(Xtest.shape)
print(Ytest.shape)

Train Set shape:
(2999, 31)
(2999, 1)
Test Set shape:
(12918, 31)
(12918, 1)


In [43]:
# OneHotEncoding on Train
ohe = OneHotEncoder(handle_unknown='ignore',sparse=False)
Xcat = pd.DataFrame(ohe.fit_transform(Xtrain[categoricalFeatures]), columns=ohe.get_feature_names_out(input_features=categoricalFeatures), index=Xtrain.index)
Xtrain = pd.concat([Xtrain,Xcat],axis=1)
Xtrain.drop(labels=categoricalFeatures,axis=1,inplace=True)
Xtrain.sample(5)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
438             2                   2   48         16         400   
1463            2                   2   32          9         400   
815             3                   3   30          8         400   
433             2                   3   42          4         400   
1531            3                   3   45          4         400   

      DRIVERRATING  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  ...  \
438              4  1994        0.0        0.0        1.0  ...   
1463             4  1995        0.0        0.0        0.0  ...   
815              4  1995        0.0        0.0        0.0  ...   
433              1  1994        0.0        0.0        0.0  ...   
1531             4  1995        0.0        0.0        0.0  ...   

      ADDRESSCHANGE_CLAIM_4_to_8_years  ADDRESSCHANGE_CLAIM_no_change  \
438                                0.0                            1.0   
1463                               0.0                            1.0   
815                                0.0                            1.0   
433                                0.0                            1.0   
1531                               0.0                            1.0   

      ADDRESSCHANGE_CLAIM_under_6_months  NUMBEROFCARS_1-vehicle  \
438                                  0.0                     1.0   
1463                                 0.0                     1.0   
815                                  0.0                     1.0   
433                                  0.0                     1.0   
1531                                 0.0                     1.0   

      NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  NUMBEROFCARS_5_to_8  \
438                       0.0                  0.0                  0.0   
1463                      0.0                  0.0                  0.0   
815                       0.0                  0.0                  0.0   
433                       0.0                  0.0                  0.0   
1531                      0.0                  0.0                  0.0   

      BASEPOLICY_All_Perils  BASEPOLICY_Collision  BASEPOLICY_Liability  
438                     0.0                   1.0                   0.0  
1463                    0.0                   0.0                   1.0  
815                     1.0                   0.0                   0.0  
433                     0.0                   1.0                   0.0  
1531                    1.0                   0.0                   0.0  

[5 rows x 139 columns]

In [44]:
# OneHotEncoding on Test
Xcat = pd.DataFrame(ohe.transform(Xtest[categoricalFeatures]), columns=ohe.get_feature_names_out(input_features=categoricalFeatures), index=Xtest.index)
Xtest = pd.concat([Xtest, Xcat], axis=1)
Xtest.drop(labels=categoricalFeatures, axis=1, inplace=True)
Xtest.sample(5)

WEEKOFMONTH  WEEKOFMONTHCLAIMED  AGE  REPNUMBER  DEDUCTIBLE  \
10626            1                   1   28         13         400   
1481             3                   2   26         14         400   
5058             4                   4   48         14         400   
3957             1                   2   32         13         400   
11173            2                   1   46          5         400   

       DRIVERRATING  YEAR  MONTH_Apr  MONTH_Aug  MONTH_Dec  ...  \
10626             4  1994        0.0        0.0        0.0  ...   
1481              3  1995        0.0        0.0        0.0  ...   
5058              4  1995        0.0        0.0        0.0  ...   
3957              3  1996        0.0        0.0        0.0  ...   
11173             1  1995        0.0        0.0        0.0  ...   

       ADDRESSCHANGE_CLAIM_4_to_8_years  ADDRESSCHANGE_CLAIM_no_change  \
10626                               0.0                            1.0   
1481                                1.0                            0.0   
5058                                0.0                            1.0   
3957                                0.0                            1.0   
11173                               0.0                            1.0   

       ADDRESSCHANGE_CLAIM_under_6_months  NUMBEROFCARS_1-vehicle  \
10626                                 0.0                     1.0   
1481                                  0.0                     0.0   
5058                                  0.0                     1.0   
3957                                  0.0                     1.0   
11173                                 0.0                     1.0   

       NUMBEROFCARS_2-vehicles  NUMBEROFCARS_3_to_4  NUMBEROFCARS_5_to_8  \
10626                      0.0                  0.0                  0.0   
1481                       1.0                  0.0                  0.0   
5058                       0.0                  0.0                  0.0   
3957                       0.0                  0.0                  0.0   
11173                      0.0                  0.0                  0.0   

       BASEPOLICY_All_Perils  BASEPOLICY_Collision  BASEPOLICY_Liability  
10626                    0.0                   0.0                   1.0  
1481                     0.0                   1.0                   0.0  
5058                     0.0                   1.0                   0.0  
3957                     0.0                   1.0                   0.0  
11173                    0.0                   1.0                   0.0  

[5 rows x 139 columns]

In [45]:
dt = DecisionTreeClassifier()
dt.fit(Xtrain, Ytrain)

DecisionTreeClassifier()

In [46]:
rf = RandomForestClassifier()
rf.fit(Xtrain, Ytrain)

<ipython-input-46-ab3867a8f796>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(Xtrain, Ytrain)


RandomForestClassifier()

In [47]:
# Predictions on the test and train data using Decision Tree model
X_test_pred = dt.predict(Xtest)
X_train_pred = dt.predict(Xtrain)

# Model Accuracy
print('Basic Decision Tree')
print("Train Accuracy:", metrics.accuracy_score(Ytrain, X_train_pred))
print("Test Accuracy:", metrics.accuracy_score(Ytest, X_test_pred))

# Confusion Matrix for Decision Tree
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest, X_test_pred))

# Max Depth and Number of Leaves in the Decision Tree
print("Max Depth:", dt.get_depth())
print("Number of Leaves:", dt.get_n_leaves())

# Printing precision, recall, and other classification metrics
print('Printing precision, recall, and other metrics')
print(metrics.classification_report(Ytest, X_test_pred))

Basic Decision Tree
Train Accuracy: 1.0
Test Accuracy: 0.8781545130825205
Confusion Matrix for Decision Tree:
[[10894  1526]
 [   48   450]]
Max Depth: 24
Number of Leaves: 288
Printing precision, recall, and other metrics
              precision    recall  f1-score   support

          No       1.00      0.88      0.93     12420
         Yes       0.23      0.90      0.36       498

    accuracy                           0.88     12918
   macro avg       0.61      0.89      0.65     12918
weighted avg       0.97      0.88      0.91     12918



In [48]:
X_testPred1 = rf.predict(Xtest)
XPred1 = rf.predict(Xtrain)
#Model Accuracy
print("Basic Random Forest")
print("Train Accuracy:", metrics.accuracy_score(Ytrain,XPred1))
print("Test Accuracy:", metrics.accuracy_score(Ytest,X_testPred1))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(Ytest,X_testPred1))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, X_testPred1))


Basic Random Forest
Train Accuracy: 1.0
Test Accuracy: 0.9622232543737421
Confusion Matrix for Random Forest:
[[12011   409]
 [   79   419]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.99      0.97      0.98     12420
         Yes       0.51      0.84      0.63       498

    accuracy                           0.96     12918
   macro avg       0.75      0.90      0.81     12918
weighted avg       0.97      0.96      0.97     12918



In [49]:
#Hyperparameter tuning done for decision tree classifier
#RANDOM SEARCH
import time
start_time = time.time()

print("RandomizedSearchCV-Decision tree")
parameters={'min_samples_leaf' : range(10,300,10),'max_depth':
            range(1,50,2),'criterion':['gini','entropy','log_loss'],
            'max_features' :range(10,30,20),'max_leaf_nodes': range(10,20,2)}
dt_random = RandomizedSearchCV(dt,parameters,n_iter=25,cv=5)
dt_random.fit(Xtrain, Ytrain)
grid_parm=dt_random.best_params_
print(grid_parm)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Decision tree
{'min_samples_leaf': 260, 'max_leaf_nodes': 18, 'max_features': 10, 'max_depth': 3, 'criterion': 'entropy'}
accuracy Score for Decision Tree:0.961449
--- 4.019765138626099 seconds ---


In [50]:
#GRID SEARCH----------------------------------------

import time
start_time = time.time()

print("GridSearchCV-Decision tree")
dt_grid = GridSearchCV(dt,parameters)
dt_grid.fit(Xtrain, Ytrain)
grid_parm1=dt_grid.best_params_
print(grid_parm1)
print("accuracy Score for Decision Tree:{0:6f}".
      format(dt_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

GridSearchCV-Decision tree
{'criterion': 'log_loss', 'max_depth': 27, 'max_features': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 10}
accuracy Score for Decision Tree:0.961449
--- 946.9934620857239 seconds ---


In [51]:
#Using the parameters obtained from HyperParameterTuning in the DecisionTreeClassifier
dtRand = DecisionTreeClassifier(**grid_parm)
dtGrid = DecisionTreeClassifier(**grid_parm1)

dtRand.fit(Xtrain,Ytrain)
dtRand_predict = dtRand.predict(Xtest)
dtGrid.fit(Xtrain,Ytrain)
dtGrid_predict = dtGrid.predict(Xtest)

In [52]:
# Accuracy for Decision Tree using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtRand_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtRand_predict))
print('Cross validation score for stratified 5 fold')
clf_cv_score = cross_val_score(dtRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9614491407338597
Confusion Matrix for Decision Tree:
[[12420     0]
 [  498     0]]
Printing the precision and recall, among other metrics


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

          No       0.96      1.00      0.98     12420
         Yes       0.00      0.00      0.00       498

    accuracy                           0.96     12918
   macro avg       0.48      0.50      0.49     12918
weighted avg       0.92      0.96      0.94     12918

Cross validation score for stratified 5 fold
[0.5 0.5 0.5 0.5 0.5]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [53]:
# Accuracy for Decision Tree using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,dtGrid_predict))
print("Confusion Matrix for Decision Tree:")
print(confusion_matrix(Ytest,dtGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, dtGrid_predict))
print('Cross validation score for stratified 5 fold')
clf_cv_score = cross_val_score(dtGrid, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)


Test Accuracy: 0.8903080972286732
Confusion Matrix for Decision Tree:
[[11365  1055]
 [  362   136]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.92      0.94     12420
         Yes       0.11      0.27      0.16       498

    accuracy                           0.89     12918
   macro avg       0.54      0.59      0.55     12918
weighted avg       0.94      0.89      0.91     12918

Cross validation score for stratified 5 fold
[0.54807692 0.5        0.54375    0.49903846 0.50632911]


In [54]:
#Hyperparameter tuning done for random forest classifier

#RANDOM SEARCH--------------------------------------------

import time
start_time = time.time()

print("RandomizedSearchCV-Random forest")
rand_parameters={'min_samples_leaf' : range(10,100,10),'max_depth':
            range(1,10,2),'max_features':[10,20,30],'n_estimators':[20,30,40]}
rf_random = RandomizedSearchCV(rf,rand_parameters,n_iter=25,cv=5)
rf_random.fit(Xtrain, Ytrain)
grid_parm=rf_random.best_params_
print(grid_parm)
print("accuracy Score for Random Forest:{0:6f}".
      format(rf_random.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))

RandomizedSearchCV-Random forest


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

{'n_estimators': 30, 'min_samples_leaf': 20, 'max_features': 30, 'max_depth': 7}
accuracy Score for Random Forest:0.929091
--- 14.637121677398682 seconds ---


In [55]:
import time
start_time = time.time()

print("GridSearchCV-Random Forest")
rf_grid = GridSearchCV(rf,rand_parameters)
rf_grid.fit(Xtrain, Ytrain)
grid_parm1=rf_grid.best_params_
print(grid_parm1)
print("accuracy Score for Random Foret:{0:6f}".
      format(rf_grid.score(Xtest,Ytest)))

print("--- %s seconds ---" % (time.time() - start_time))


GridSearchCV-Random Forest


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

{'max_depth': 5, 'max_features': 30, 'min_samples_leaf': 10, 'n_estimators': 30}
accuracy Score for Random Foret:0.940084
--- 211.84791541099548 seconds ---


In [56]:
#Using the parameters obtained from HyperParameterTuning in the RandomForestClassifier
rfRand = RandomForestClassifier(**grid_parm)
rfGrid = RandomForestClassifier(**grid_parm1)

rfRand.fit(Xtrain,Ytrain)
rfRand_predict = rfRand.predict(Xtest)
rfGrid.fit(Xtrain,Ytrain)
rfGrid_predict = rfGrid.predict(Xtest)

<ipython-input-56-18b8c44979a6>:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfRand.fit(Xtrain,Ytrain)
<ipython-input-56-18b8c44979a6>:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfGrid.fit(Xtrain,Ytrain)


In [57]:
# Accuracy for Random Forest using Random Search CV for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfRand_predict))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(Ytest,rfRand_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfRand_predict))
print('cross validation score for random forst')
clf_cv_score = cross_val_score(rfRand, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)


Test Accuracy: 0.934355163337978
Confusion Matrix for Random Forest:
[[11955   465]
 [  383   115]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.96      0.97     12420
         Yes       0.20      0.23      0.21       498

    accuracy                           0.93     12918
   macro avg       0.58      0.60      0.59     12918
weighted avg       0.94      0.93      0.94     12918

cross validation score for random forst


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

[0.74615385 0.73557692 0.54375    0.5        0.55063291]


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)


In [58]:
# Accuracy for Random Forest using Grid Search for Hyperparameter Tuning

print("Test Accuracy:", metrics.accuracy_score(Ytest,rfGrid_predict))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(Ytest,rfGrid_predict))
print('Printing the precision and recall, among other metrics')
print(metrics.classification_report(Ytest, rfGrid_predict))
print('cross validation score')
clf_cv_score = cross_val_score(rfGrid, Xtrain, Ytrain, cv=5, scoring="balanced_accuracy")
print(clf_cv_score)

Test Accuracy: 0.9388450224492956
Confusion Matrix for Random Forest:
[[12021   399]
 [  391   107]]
Printing the precision and recall, among other metrics
              precision    recall  f1-score   support

          No       0.97      0.97      0.97     12420
         Yes       0.21      0.21      0.21       498

    accuracy                           0.94     12918
   macro avg       0.59      0.59      0.59     12918
weighted avg       0.94      0.94      0.94     12918

cross validation score


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:686: DataConversionWarning: A column-vector y was passed whe

[0.68076923 0.70480769 0.54375    0.5        0.55696203]
